apiVersion: v1
kind: ConfigMap
metadata:
  name: cinematheque-config
  namespace: cinematheque
data:
  NODE_ENV: "production"
  PORT: "3000"
  FRONTEND_URL: "http://localhost:8080"
  MINIO_ENDPOINT: "minio"
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_BUCKET: "movie-images"
  KAFKA_BROKERS: "kafka:9092"
  KAFKA_TOPIC: "cinematheque.events"
